### ISSUE TITLE
Setup CI CD pipeline for ESP8266 build for esp8266_flash

### ISSUE THREAD

**Issue by revantharunachalam** [revantharunachalam/easy-electronics-esp-relay#1]
### Major features:
- [x] 1. Updated Arduino CLI version.
- [x] 2. Error in flashing file directory name. Rename (pwd)/es8266-flash to (pwd)\esp8266-flash.
- [x] 3. No Platform and FQBN detected for esp8266:esp8266.
- [x] 4. Error in a clean build.
- [ ] 5. Test PySerial wrapper.
- [ ] 6. Flash and test .ino file in esp8266 remotely.

### Additional features:
- [x] 1. Update build.cmd for local execution.

**Comment by revantharunachalam** [comment]
**[Task 3]**: Issue in updating the index for ESP8266.
- `arduino-cli core update-index --config-file esp8266_flash-cli.yaml` command is not reflected in the execution.
- Need to check, if the package_index.json file is fetching from the esp8266_flash-cli.yaml, or else manually check with the inline command: 
**Reference:** 
`arduino-cli config add board_manager.additional_urls http://arduino.esp8266.com/stable/package_esp8266com_index.json`

**Comment by revantharunachalam** [comment]
Platform-related files were downloaded, and platform detection was done in commit: 72730dd13e08c914615cb963fdb184017cb38e74. 👍 

**[Task 3]**: Done

**Comment by revantharunachalam** [comment]
CI/CD pipeline up and running with commit: [1eea95b](https://github.com/revantharunachalam/easy-electronics-esp-relay/commit/1eea95bc073818e474d5e516a60a61db87639fe5)

### [Closing Ticket]

**Comment by revantharunachalam** [comment]
### We are reopening the ticket for CI/CD enhancement. 🔔
